apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow
  namespace: admo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-job-role
  namespace: admo
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-job-binding
  namespace: admo
subjects:
  - kind: ServiceAccount
    name: airflow
    namespace: admo
roleRef:
  kind: Role
  name: airflow-job-role
  apiGroup: rbac.authorization.k8s.io
