apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
  namespace: admo
type: Opaque
stringData:
  POSTGRES_USER: admo
  POSTGRES_PASSWORD: admo123
  POSTGRES_DB: admo
  ADMO_DATABASE_URI: postgresql+psycopg://admo:admo123@postgres:5432/admo
---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-creds
  namespace: admo
type: Opaque
stringData:
  MLFLOW_DATABASE_URI: postgresql+psycopg://admo:admo123@postgres:5432/mlflow
---
apiVersion: v1
kind: Secret
metadata:
  name: garage-creds
  namespace: admo
type: Opaque
stringData:
  GARAGE_DEFAULT_ACCESS_KEY: GKADMOSECRETKEY123
  GARAGE_DEFAULT_SECRET_KEY: admo123
  GARAGE_DEFAULT_BUCKET: admo
  GARAGE_DEFAULT_REGION: garage
  GARAGE_RPC_SECRET: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
  AWS_ACCESS_KEY_ID: GKADMOSECRETKEY123
  AWS_SECRET_ACCESS_KEY: admo123
  AWS_DEFAULT_REGION: garage
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-creds
  namespace: admo
type: Opaque
stringData:
  AIRFLOW_JWT_SECRET: admo123
  AIRFLOW_DATABASE_URI: postgresql+psycopg://admo:admo123@postgres:5432/airflow
